# Generated by Django 5.0.2 on 2024-10-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prebuilt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.prebuilt'),
        ),
    ]
