# Generated by Django 5.0.2 on 2024-10-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0002_cart_prebuilt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='prebuilt',
        ),
    ]
