# Generated by Django 5.0.2 on 2024-10-16 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0011_cart_prebuilt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prebuilt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.prebuilt'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.product'),
        ),
    ]
