# Generated by Django 5.0.2 on 2024-10-16 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0013_remove_cart_prebuilt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrebuiltCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('prebuilt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_app.prebuilt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_app.user')),
            ],
        ),
    ]
