# Generated by Django 5.0.2 on 2024-10-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0015_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
