# Generated by Django 5.0.2 on 2024-10-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0017_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prebuiltcart',
            name='prebuilt',
        ),
        migrations.RemoveField(
            model_name='prebuiltcart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PrebuiltCart',
        ),
    ]
