# Generated by Django 5.0.2 on 2024-10-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0018_remove_prebuiltcart_prebuilt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prebuilt',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
