# Generated by Django 5.0.2 on 2024-10-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0019_delete_prebuilt_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='pc_app.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc_app.user')),
            ],
        ),
    ]
