# Generated by Django 5.0.2 on 2024-10-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0021_remove_order_items_remove_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='pc_app.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
