# Generated by Django 5.0.2 on 2024-10-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0022_remove_order_status_order_items_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pc_app.product'),
        ),
    ]
