# Generated by Django 5.0.2 on 2024-10-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0023_order_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_product',
        ),
    ]
