# Generated by Django 5.0.2 on 2024-10-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0025_order_status_remove_order_items_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='product',
        ),
    ]
