# Generated by Django 5.0.2 on 2024-10-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0028_remove_order_cart_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Product Returned', 'Product Returned')], default='Pending', max_length=20),
        ),
    ]
