# Generated by Django 5.0.2 on 2024-10-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_app', '0033_remove_services_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
